AWX:
  # enable use of awx-deploy template
  enabled: true
  name: awx
  spec:
    admin_user: admin
    postgres_configuration_secret: awx-postgres-configuration

  # configurations for external postgres instance
  postgres:
    enabled: true
    host: postgres-service.awx.svc.cluster.local
    port: 5678
    dbName: awx
    username: myuser
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: mypassword
    sslmode: disable
    type: unmanaged
